### PR TITLE
(feat) Add sinek kafka lib binary dependencies

### PR DESCRIPTION
**Pull request by brent-hoover**

### CODE REVIEW

**Review by impactmass — DISMISSED** [review]
👍 LGTM

Info: This is adding binaries for kafka drivers used in the Reaction API code. The binaries are preferred, but if the binaries are not found the JS implementation is used.

**Review by ticean — COMMENTED** [review]
Should the libs be installed in all versions? Would this be used by plugins? If so, can we guarantee or at least expect that the plugins will only be used with the Meteor 1.8 image? There's nothing Meteor specific about these inclusions.

On the other hand, adding to all could bust docker caches and add some file size to all the images where it might not be used.

I'm OK with either outcome, and asking to make sure we consider and document the choice in this PR.

**Comment by impactmass** [comment]
@ticean good questions.

I lean to adding this to a latest release and later add to other versions as needed. 

But, the other versioning issue which we discussed briefly is also important before merging this. Merging this as it is right now will create a new base image for 1.8-meteor. Ideally it should be a new version (shouldn't be busting the old). 

We had intended this to just be a meteor base, that's why we had the versioning tied that way. We would have to decide if we still want that to be true now that we are adding non-meteor deps.

For this PR not to be blocked though, there's a patch meteor update 1.8.0.2 that we can attach this to. I only propose this as a temporary solution.

**Review by ticean — DISMISSED** [review]
Sounds good!

**Comment by impactmass** [comment]
@ticean I'll make that adjustment and push it to this branch. But we need to adjust the GitHub PR checks/setting. It looks like the `ci/circleci: docker-build` and `ci/circleci: test` checks are not reporting, thus will prevent a merge. I think the workflow is to replace those two as required. Needs an admin

**Review by ticean — APPROVED** [review]

**Pull request merged**
