### PR TITLE
Meteor 1.8 final 

### LINKED ISSUE #35: Create image for Meteor 1.8
## Create image for Meteor 1.8 rc

Instructions to create from project's Readme:
- Create a directory for the new version (following the existing name convention)
- Update the new Dockerfile as needed.
- Set the TAGS ENV in the `options` file to your release TAG
- Set the Meteor version ENV in the `options` file
- If this new version is the highest tag, search for and remove `latest` from the current options file it's located, and add it to the new options file
- Add any extra test step(s) needed in the `test-script.sh`
- Update `History.md` with the new release
- Open a PR to master with the changes.

### PR DESCRIPTION
**Pull request by impactmass**
Resolves #35 

## Publish v1.8-meteor
- Update Meteor version to 1.8
- Update node version to 8.11.4

## To review:
- Confirm that each step of making a new version listed [here](https://github.com/reactioncommerce/base#adding-a-new-version-creating-a-new-release) was followed correctly.

### CODE REVIEW

**Review by nnnnat — APPROVED** [review]
I think this looks good but I'll let @ticean merge

**Review by ticean — APPROVED** [review]
Looks good to me!

**Comment by aldeed** [comment]
@impactmass Could we add this command that is currently in the Reaction dockerfile to this dockerfile instead?

```
# Because Docker Compose uses a named volume for node_modules and named volumes are owned
# by root by default, we have to initially create node_modules here with correct owner.
# Without this NPM cannot write packages into node_modules later, when running in a container.
RUN mkdir "$APP_SOURCE_DIR/node_modules" && chown node "$APP_SOURCE_DIR/node_modules"
```

Anywhere after `USER node`

If we do this, we should be able to use this image directly in the Reaction docker-compose and will not need the Reaction Dockerfile for development purposes

**Comment by ticean** [comment]
@aldeed could we discuss the Dockerfile modification in a separate issue so that it doesn't block this merge? It isn't directly related to the Meteor upgrade.

**Comment by impactmass** [comment]
@aldeed @ticean thanks for the comments. I remember you mentioned this earlier, I just wanted to keep it separate. We can do that in #37.

**Pull request merged**
